#!/usr/bin/env bash
# Install LAMP stack (Apache, PHP; MySQL client only, since DB is on Cloud SQL)

sudo apt install -y apache2 php libapache2-mod-php php-mysql php-gd php-xml php-mbstring php-intl php-curl php-zip php-soap mariadb-client
sudo a2enmod rewrite  # Enable mod_rewrite for PrestaShop
sudo systemctl restart apache2
